name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test (plenary.busted)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Neovim
        uses: rhysd/action-setup-vim@febef33995d6649302e9d88dda81e071b68f16a7 # v1.6.1
        with:
          neovim: true
          version: v0.11.2

      - name: Run tests
        run: make test
